-- Mata pelajaran

CREATE TABLE public.mata_pelajaran (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    kode text NOT NULL,
    tingkat int NOT NULL,

    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE ONLY public.mata_pelajaran
    ADD CONSTRAINT mata_pelajaran_pkey PRIMARY KEY (id);

-- Wali Kelas
CREATE TABLE public.wali_kelas (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    alamat text NOT NULL,
    telpon text NOT NULL,

    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE ONLY public.wali_kelas 
    ADD CONSTRAINT wali_kelas_pkey PRIMARY KEY (id);
	
-- Kelas
CREATE TABLE public.kelas (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    tingkat int NOT NULL,

    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE ONLY public.kelas 
    ADD CONSTRAINT kelas_pkey PRIMARY KEY (id);
	
-- Jam Pelajaran
CREATE TABLE public.jam_pelajaran (
    id int GENERATED BY DEFAULT AS IDENTITY,
    id_mata_pelajaran int NOT NULL,
    jam_mulai text NOT NULL,
    jam_akhir text NOT NULL,

    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE ONLY public.jam_pelajaran 
    ADD CONSTRAINT jam_pelajaran_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.jam_pelajaran
    ADD CONSTRAINT mataPelajaran_jamPelajaran_idMataPelajaran_foreign FOREIGN KEY (id_mata_pelajaran) REFERENCES public.mata_pelajaran(id);

-- Siswa
CREATE TABLE public.siswa (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    id_kelas int NOT NULL,
    id_wali_kelas int NOT NULL,
    tingkat int NOT NULL,
    alamat text NOT NULL,

    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone 
);

ALTER TABLE ONLY public.siswa   
    ADD CONSTRAINT siswa_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.siswa
    ADD CONSTRAINT kelas_siswa_idKelas_foreign FOREIGN KEY (id_kelas) REFERENCES public.kelas(id);

ALTER TABLE ONLY public.siswa
    ADD CONSTRAINT waliKelas_siswa_idWaliKelas_foreign FOREIGN KEY (id_wali_kelas) REFERENCES public.wali_kelas(id);
	
-- Jam pelajaran siswa
CREATE TABLE public.jam_pelajaran_siswa (
    id int GENERATED BY DEFAULT AS IDENTITY,
    id_jam_pelajaran int NOT NULL,
    id_siswa int NOT NULL,
    status text NOT NULL,

    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone 
);

ALTER TABLE ONLY public.jam_pelajaran_siswa 
    ADD CONSTRAINT jam_pelajaran_siswa_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.jam_pelajaran_siswa
    ADD CONSTRAINT jamPelajaran_jamPelajaranSiswa_idJamPelajaranSiswa_foreign FOREIGN KEY (id_jam_pelajaran) REFERENCES public.jam_pelajaran(id);

ALTER TABLE ONLY public.jam_pelajaran_siswa
    ADD CONSTRAINT siswa_jamPelajaranSiswa_idSiswa_foreign FOREIGN KEY (id_siswa) REFERENCES public.siswa(id);