-- mata pelajaran
CREATE TABLE public.mata_pelajaran(
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    kode text NOT NULL,
    tingkat int NOT NULL,
    create_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    delete_at timestamp with time zone
);

ALTER TABLE ONLY public.mata_pelajaran
    ADD CONSTRAINT mata_pelajaran_pkey PRIMARY KEY (id);

-- kelas
CREATE TABLE public.kelas(
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    tingkat int not NULL,
    create_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    delete_at timestamp with time zone
);

ALTER TABLE ONLY public.kelas
    ADD CONSTRAINT kelas_pkey PRIMARY KEY (id);


-- wali_kelas
CREATE TABLE public.wali_kelas(
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    alamat text NOT NULL,
    telpon text NOT NULL,
    create_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    delete_at timestamp with time zone
);
ALTER TABLE ONLY public.wali_kelas
    ADD CONSTRAINT wali_kelas_pkey PRIMARY KEY (id);
-- siswa
CREATE TABLE public.siswa(
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    id_kelas int NOT NULL,
    id_wali_kelas int NOT NULL,
    tingkat int not NULL,
    alamat text,
    create_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    delete_at timestamp with time zone
);
ALTER TABLE ONLY public.siswa
    ADD CONSTRAINT siswa_pkey PRIMARY KEY (id);

-- jam pelajaran
CREATE TABLE public.jam_pelajaran(
    id int GENERATED BY DEFAULT AS IDENTITY,
    id_mapel int NOT NULL,
    jam_mulai text NOT NULL,
    jam_akhir text NOT NULL,
    create_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    delete_at timestamp with time zone
);
ALTER TABLE ONLY public.jam_pelajaran
    ADD CONSTRAINT jam_pelajaran_pkey PRIMARY KEY (id);

-- jam pelajaran siswa
CREATE TABLE public.jam_pelajaran_siswa(
    id int GENERATED BY DEFAULT AS IDENTITY,
    id_jam_pelajaran int NOT NULL,
    id_siswa int NOT NULL,
    status text NOT NULL,
    create_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    delete_at timestamp with time zone
);

ALTER TABLE ONLY public.jam_pelajaran_siswa
    ADD CONSTRAINT jam_pelajaran_siswa_pkey PRIMARY KEY (id);


-- ===================================================================================================================
-- foreign

-- jam pelajaran
ALTER TABLE ONLY public.jam_pelajaran
    ADD CONSTRAINT id_mapel_foreign FOREIGN KEY (id_mapel) REFERENCES public.mata_pelajaran(id);

-- jam pelajaran siswa
ALTER TABLE ONLY public.jam_pelajaran_siswa
    ADD CONSTRAINT id_jam_pelajaran_foreign FOREIGN KEY (id_jam_pelajaran) REFERENCES public.jam_pelajaran(id);
ALTER TABLE ONLY public.jam_pelajaran_siswa
    ADD CONSTRAINT id_siswa_foreign FOREIGN KEY (id_siswa) REFERENCES public.siswa(id);

-- siswa
ALTER TABLE ONLY public.siswa
    ADD CONSTRAINT kelas_siswa_id_kelas_foreign FOREIGN KEY (id_kelas) REFERENCES public.kelas(id);

ALTER TABLE ONLY public.siswa
    ADD CONSTRAINT id_wali_kelas_foreign FOREIGN KEY (id_wali_kelas) REFERENCES public.wali_kelas(id);
